### ISSUE TITLE
Consider improving smoothing blinking function (noise reduction)

### ISSUE THREAD

**Issue by adv0r** [MADE-barcelona/beacon-fi#7]
Consider using moving averages to smooth out blinking transition to reduce noise and interferences.

Take performance into account

**Comment by willblev** [comment]
pseudocode
current_value= wifi_signal_strength
smoothed=(previous_value + current_value) / 2
previous_value= current_value

**Comment by willblev** [comment]
implemented in test code in /src/scan_test/init.lua line 60
