### ISSUE TITLE
Implement the mechanism that allows beacon to switch from "Open network mode" to "SSID specific mode"

### ISSUE THREAD

**Issue by adv0r** [MADE-barcelona/beacon-fi#9]

**Comment by willblev** [comment]
pseudocode
if "familiar_SSID" in list_of_aps:        #checks if one of our APs is visible; if so, goes to 'game mode'
    wifi_signal_strength = familiar_SSID[rssi]
else:
    wifi_signal_strength = strongest_open_SSID[rssi]

**Comment by willblev** [comment]
test code written in /src/scan_test/init.lua  lines 26-40
